# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a07fa0b1d8c0a0d9712722c5e0b035b9c2d5aba42a56169c4967e7e9e9a0c778e7f717596ae0279bf04026220e1cdf91b0e9ce630bbfd1e59bbc3f8cb309099

test:
  secret_key_base: f9a32494891e1f40c54a9bccf7c9e6ad38a6f22ea312cc456518bdf360c0e502fc78c2fca50aa03124dafa72e7dd2673716eec3d949e40b7d18a5a8379e05e5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
